# backend/docker-compose.yml

version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_HOST: "db"
      DB_NAME: "${DB_NAME}"
      JWT_SECRET: "${JWT_SECRET}"
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  db_data: